### ISSUE TITLE
OpenJPEG instead of Jasper

### ISSUE THREAD

**Issue by sgillies** [sgillies/frs-wheel-builds#1]
Suggested by @rouault on gdal-dev. Looks like OpenJPEG switched to cmake around 2.0, which complicates the buildout. I'll borrow from https://github.com/libLAS/libLAS/blob/master/buildout/buildout.cfg.

**Comment by perrygeo** [comment]
Good article on JP2 driver performance here: http://blog.hexagongeospatial.com/jpeg2000-quirks/

```
- JPEG2000/Jasper is borderline useless, however this is expected given development has stalled for some time, yet people continue using it. In almost all cases the Driver would spin indefinitely decoding input. Out of 75 tests it completed only 7 and those took a significant amount of time to complete.
- JP2OpenJPEG is preferred by many users due to its BSD license and active development however it still failed 19 tests. Of the test results it did pass, memory requirements were the highest (by significant amounts) and it also remained 10x slower (or more) than the two proprietary drivers tested below.
- JP2MrSID showed 100% completion rate and very low memory usage throughout
- JP2ECW failed 2 tests however in all other results provided the fastest results, on average +12%
```

thanks @vincentsarago

**Comment by vincentsarago** [comment]
another discussion about OpenJPG : 
https://lists.osgeo.org/pipermail/gdal-dev/2015-December/043297.html

**Comment by sgillies** [comment]
After those reports, maybe I'll just drop JP2 support entirely! Proprietary libs obviously can't be shipped in these manylinux1 wheels.

**Comment by rouault** [comment]
Sentinel-2 imagery is delivered in JPEG-2000. The fact that proprietary libs perform better than openjpeg doesn't make the later useless. At least you can read the data to convert it something else.

**Comment by sgillies** [comment]
Reminder to self: https://github.com/uclouvain/openjpeg/blob/master/INSTALL.md.

**Comment by vincentsarago** [comment]
@sgillies just a quick note, to compile `openjpeg` you'll need to install `cmake>=2.8`because `manylinux` comes with `cmake==2.6`

#### fix 
```
ENV CMAKE_VERSION 2.8.10.2
RUN mkdir -p /src  \
  && cd /src \
  && curl -f -L -O http://www.cmake.org/files/v2.8/cmake-$CMAKE_VERSION.tar.gz \
  && tar -zxvf cmake-$CMAKE_VERSION.tar.gz \
  && cd /src/cmake-$CMAKE_VERSION \
  && ./configure --prefix=/usr/local \
  && make \
  && make install \
  && rm -rf /src
```
then for OpenJpeg

```
ENV OPENJPEG_VERSION 2.1.2
RUN mkdir -p /src  \
    && cd /src \
    && curl -f -L -O https://github.com/uclouvain/openjpeg/archive/v$OPENJPEG_VERSION.tar.gz  \
    && tar -zvxf v$OPENJPEG_VERSION.tar.gz \
    && cd  /src/openjpeg-$OPENJPEG_VERSION \
    && mkdir build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
    && make install && make clean \
    && rm -rf /src
```

**Comment by rouault** [comment]
> ENV OPENJPEG_VERSION 2.1.2

Please use 2.2.0 :-)

**Comment by vincentsarago** [comment]
@rouault does GDAL 2.2.1 is corrected for 2.2.0 ?

**Comment by rouault** [comment]
> does GDAL 2.2.1 is corrected for 2.2.0 ?

Ah good point. "Support" for OpenJPEG 2.2.0 be in GDAL 2.2.2. But actually that's just a matter of having a include/openjpeg-2.2 directory. You could ln -s /usr/local/include/openjpeg-2.2   /usr/local/include/openjpeg-2.1 and that will work just fine when building GDAL 2.2.1

**Comment by vincentsarago** [comment]
oh excellent! thanks @rouault

**Comment by sgillies** [comment]
Thanks, @vincentsarago and @rouault. I'm going to give this a try soon.

**Comment by sgillies** [comment]
Update: I've done it for OS X, still working on the CentOS config and build.
