### ISSUE TITLE
Change MACOSX_DEPLOYMENT_TARGET to 10.9

### ISSUE THREAD

**Issue by sgillies** [sgillies/frs-wheel-builds#15]
I've been able to build GDAL 2.1.3 on macosx with `MACOSX_DEPLOYMENT_TARGET=10.6`. This means that the wheels would work on any mac supported by python.org Pythons. New c++11 features in GDAL 2.2.0 effectively require `MACOSX_DEPLOYMENT_TARGET=10.9`.

I feel okay cutting off wheels for Mountain Lion, which is unsupported since September 2015. Any concerns @geowurster @perrygeo @rouault?

**Comment by rouault** [comment]
I have no informed opinion regarding Mac. Note that the issue with GDAL 2.2.0 you had is not directly related to C++11 (since GDAL compiles fine in non-C++11 mode with other compilers) but apparently a conflict when importing <cmath> and isnan() macro / std::isnan().

**Comment by geowurster** [comment]
@sgillies That seems reasonable.

**Comment by sgillies** [comment]
Done!
