### ISSUE TITLE
Support C++11

### ISSUE THREAD

**Issue by geowurster** [sgillies/frs-wheel-builds#25]
Relates to https://github.com/mapbox/rasterio/issues/1230 and https://github.com/Toblerity/Fiona/issues/514

GDAL 2.3 will [require C++11](https://trac.osgeo.org/gdal/changeset/40984).  Attempting to install Rasterio after this change fails with a bunch of warnings like:

```
/home/travis/gdalinstall/gdal-trunk/include/ogr_geometry.h:974:9: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
             const CPL_OVERRIDE;
             ^
```

The [Travis builds against GDAL trunk](https://travis-ci.org/mapbox/rasterio/jobs/315171560) are currently failing with the same issues.  Fiona hasn't had a Travis build since the change, but I am expecting it to fail in the same manner.

**Comment by sgillies** [comment]
Closing. We're switching to multibuild (like SciPy &c): https://github.com/sgillies/rasterio-wheels.
