### ISSUE TITLE
manylinux2010

### ISSUE THREAD

**Issue by perrygeo** [sgillies/frs-wheel-builds#30]
Centos 5, on which `manylinux1` wheels are built, is past it's end of life.

There's an active PEP to upgrade the wheel building system to Centos 6, dubbed `manylinux2010` https://www.python.org/dev/peps/pep-0571/

**Comment by sgillies** [comment]
Yeah, I've been following the discussion. Much of it was about switching to [CalVer](https://calver.org/): "manylinux2010" instead of "manylinux2". I've been waiting until other projects move, but that's going to start happening soon!

**Comment by vincentsarago** [comment]
FYI: just noting that to be able to compile GDAL 2.3 we need gcc > 5.2 which I don't think is shipped with centos 6 (manylinux) by default. 

Steps to install GCC 5.5 on centos 6 
```
RUN yum install libmpc-devel mpfr-devel gmp-devel -y

ENV GCC_VERSION=5.5.0
RUN curl -o "gcc-${GCC_VERSION}.tar.gz" https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz \
  && tar xvzf "gcc-${GCC_VERSION}.tar.gz" \
  && cd gcc-${GCC_VERSION} \
  && ./configure --with-system-zlib --disable-multilib --enable-languages=c,c++ \
  && make -j 8 && make install
```

Edits: some of the errors I was getting are mentioned here https://lists.osgeo.org/pipermail/gdal-dev/2018-May/048581.html

**Comment by sgillies** [comment]
@vincentsarago thanks for the lead! It'll be interesting to see if there are implications for the linux wheels.

**Comment by sgillies** [comment]
Closing. We're switching to multibuild (like SciPy &c): https://github.com/sgillies/rasterio-wheels.
